name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: ULPF CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Download dependencies
        run: go mod download

      - name: Check Go formatting
        run: |
          UNFORMATTED=$(gofmt -l .)
          if [ -n "$UNFORMATTED" ]; then
            echo "Error: The following Go files are not formatted according to gofmt:"
            echo "$UNFORMATTED"
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Run all tests
        run: go test -v ./...

      - name: Build Ingestion Service
        run: go build ./cmd/ingestion

      - name: Build Worker Service
        run: go build ./cmd/worker
